name: Update docs
on:
  push:
    paths:
      - 'README.md'
    branches:
      - main
  workflow_dispatch:

jobs:
  dispatch:
    name: Send repository dispatch
    runs-on: ubuntu-22.04
    steps:
      - uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.REPO_DISPATCH_PAT }}
          repository: EndBug/game-tracker-docs
          event-type: docs-update
