name: Update docs
on: push

jobs: 
  run:
    name: Update documentation
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@master

    - name: Set up Node.js
      uses: actions/setup-node@master
      with:
        node-version: 8.9.4
    
    - name: Install dependencies
      run: npm install --only=dev && npm install ts-node --no-save

    - name: Update documentation
      run: npm run doc

    - name: Commit documentation changes
      uses: EndBug/add-and-commit@latest
      with:
        author_name: Federico Grandi
        author_email: fgrandi30@gmail.com
        message: "[auto] Update documentation"
        path: doc
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
