name: Update docs
on: push

jobs: 
  run:
    name: Run npm script
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@master

    - name: Set up Node.js 10.x
      uses: actions/setup-node@master
      with:
        node-version: 10.x
    
    - name: Install dependencies
      run: npm install --only=dev && npm i ts-node

    - name: Run script
      run: npm run doc

    - name: Auto-commit changed files
      uses: elstudio/actions-js-build/commit@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WD_PATH: ./doc
